/**
 * Test `typesMatch`.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as AasTypes from "../src/types";
import * as TestCommonJsonization from "./commonJsonization";

const THE_BRANCH = TestCommonJsonization.loadMinimalBranch();

const THE_LEAF = TestCommonJsonization.loadMinimalLeaf();

const THE_BLOSSOM = TestCommonJsonization.loadMinimalBlossom();

const THE_CONTAINER = TestCommonJsonization.loadMinimalContainer();

test("type matches for Branch", () => {
  expect(
    AasTypes.typesMatch(
      THE_BRANCH,
      THE_BRANCH
    )
  ).toStrictEqual(true);

  expect(
    AasTypes.typesMatch(
      THE_BRANCH,
      THE_LEAF
    )
  ).toStrictEqual(true);

  expect(
    AasTypes.typesMatch(
      THE_BRANCH,
      THE_BLOSSOM
    )
  ).toStrictEqual(true);

  expect(
    AasTypes.typesMatch(
      THE_BRANCH,
      THE_CONTAINER
    )
  ).toStrictEqual(false);
});

test("type matches for Leaf", () => {
  expect(
    AasTypes.typesMatch(
      THE_LEAF,
      THE_BRANCH
    )
  ).toStrictEqual(false);

  expect(
    AasTypes.typesMatch(
      THE_LEAF,
      THE_LEAF
    )
  ).toStrictEqual(true);

  expect(
    AasTypes.typesMatch(
      THE_LEAF,
      THE_BLOSSOM
    )
  ).toStrictEqual(true);

  expect(
    AasTypes.typesMatch(
      THE_LEAF,
      THE_CONTAINER
    )
  ).toStrictEqual(false);
});

test("type matches for Blossom", () => {
  expect(
    AasTypes.typesMatch(
      THE_BLOSSOM,
      THE_BRANCH
    )
  ).toStrictEqual(false);

  expect(
    AasTypes.typesMatch(
      THE_BLOSSOM,
      THE_LEAF
    )
  ).toStrictEqual(false);

  expect(
    AasTypes.typesMatch(
      THE_BLOSSOM,
      THE_BLOSSOM
    )
  ).toStrictEqual(true);

  expect(
    AasTypes.typesMatch(
      THE_BLOSSOM,
      THE_CONTAINER
    )
  ).toStrictEqual(false);
});

test("type matches for Container", () => {
  expect(
    AasTypes.typesMatch(
      THE_CONTAINER,
      THE_BRANCH
    )
  ).toStrictEqual(false);

  expect(
    AasTypes.typesMatch(
      THE_CONTAINER,
      THE_LEAF
    )
  ).toStrictEqual(false);

  expect(
    AasTypes.typesMatch(
      THE_CONTAINER,
      THE_BLOSSOM
    )
  ).toStrictEqual(false);

  expect(
    AasTypes.typesMatch(
      THE_CONTAINER,
      THE_CONTAINER
    )
  ).toStrictEqual(true);
});

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
