/**
 * Test `as*` and `is*` functions.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as AasTypes from "../src/types";
import * as TestCommonJsonization from "./commonJsonization";

test("casts over an instance of Branch", () => {
  const theBranch =
    TestCommonJsonization.loadMinimalBranch();

  expect(
    AasTypes.isNode(theBranch)
  ).toStrictEqual(true);
  expect(
    AasTypes.asNode(theBranch)
  ).toStrictEqual(theBranch);

  expect(
    AasTypes.isBranch(theBranch)
  ).toStrictEqual(true);
  expect(
    AasTypes.asBranch(theBranch)
  ).toStrictEqual(theBranch);

  expect(
    AasTypes.isLeaf(theBranch)
  ).toStrictEqual(false);
  expect(
    AasTypes.asLeaf(theBranch)
  ).toBeNull();

  expect(
    AasTypes.isBlossom(theBranch)
  ).toStrictEqual(false);
  expect(
    AasTypes.asBlossom(theBranch)
  ).toBeNull();

  expect(
    AasTypes.isContainer(theBranch)
  ).toStrictEqual(false);
  expect(
    AasTypes.asContainer(theBranch)
  ).toBeNull();
});

test("casts over an instance of Leaf", () => {
  const theLeaf =
    TestCommonJsonization.loadMinimalLeaf();

  expect(
    AasTypes.isNode(theLeaf)
  ).toStrictEqual(true);
  expect(
    AasTypes.asNode(theLeaf)
  ).toStrictEqual(theLeaf);

  expect(
    AasTypes.isBranch(theLeaf)
  ).toStrictEqual(true);
  expect(
    AasTypes.asBranch(theLeaf)
  ).toStrictEqual(theLeaf);

  expect(
    AasTypes.isLeaf(theLeaf)
  ).toStrictEqual(true);
  expect(
    AasTypes.asLeaf(theLeaf)
  ).toStrictEqual(theLeaf);

  expect(
    AasTypes.isBlossom(theLeaf)
  ).toStrictEqual(false);
  expect(
    AasTypes.asBlossom(theLeaf)
  ).toBeNull();

  expect(
    AasTypes.isContainer(theLeaf)
  ).toStrictEqual(false);
  expect(
    AasTypes.asContainer(theLeaf)
  ).toBeNull();
});

test("casts over an instance of Blossom", () => {
  const theBlossom =
    TestCommonJsonization.loadMinimalBlossom();

  expect(
    AasTypes.isNode(theBlossom)
  ).toStrictEqual(true);
  expect(
    AasTypes.asNode(theBlossom)
  ).toStrictEqual(theBlossom);

  expect(
    AasTypes.isBranch(theBlossom)
  ).toStrictEqual(true);
  expect(
    AasTypes.asBranch(theBlossom)
  ).toStrictEqual(theBlossom);

  expect(
    AasTypes.isLeaf(theBlossom)
  ).toStrictEqual(true);
  expect(
    AasTypes.asLeaf(theBlossom)
  ).toStrictEqual(theBlossom);

  expect(
    AasTypes.isBlossom(theBlossom)
  ).toStrictEqual(true);
  expect(
    AasTypes.asBlossom(theBlossom)
  ).toStrictEqual(theBlossom);

  expect(
    AasTypes.isContainer(theBlossom)
  ).toStrictEqual(false);
  expect(
    AasTypes.asContainer(theBlossom)
  ).toBeNull();
});

test("casts over an instance of Container", () => {
  const theContainer =
    TestCommonJsonization.loadMinimalContainer();

  expect(
    AasTypes.isNode(theContainer)
  ).toStrictEqual(false);
  expect(
    AasTypes.asNode(theContainer)
  ).toBeNull();

  expect(
    AasTypes.isBranch(theContainer)
  ).toStrictEqual(false);
  expect(
    AasTypes.asBranch(theContainer)
  ).toBeNull();

  expect(
    AasTypes.isLeaf(theContainer)
  ).toStrictEqual(false);
  expect(
    AasTypes.asLeaf(theContainer)
  ).toBeNull();

  expect(
    AasTypes.isBlossom(theContainer)
  ).toStrictEqual(false);
  expect(
    AasTypes.asBlossom(theContainer)
  ).toBeNull();

  expect(
    AasTypes.isContainer(theContainer)
  ).toStrictEqual(true);
  expect(
    AasTypes.asContainer(theContainer)
  ).toStrictEqual(theContainer);
});

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
